import { EnemyType } from '../types';
import type { EnemyDefinition } from '../types';
import { COLORS } from '../constants';

export const EnemyDefinitions: Record<EnemyType, EnemyDefinition> = {
  [EnemyType.PingFlood]: {
    type: EnemyType.PingFlood,
    name: 'Ping Flood',
    hp: 30,
    speed: 60,
    damageToHub: 5,
    reward: 10,
    stealth: false,
    armor: 0,
    color: COLORS.pingFlood,
    size: 8,
    spawnCooldown: 0,
  },
  [EnemyType.Trojan]: {
    type: EnemyType.Trojan,
    name: 'Trojan',
    hp: 50,
    speed: 40,
    damageToHub: 10,
    reward: 15,
    stealth: true,
    armor: 0,
    color: COLORS.trojan,
    size: 10,
    spawnCooldown: 0,
  },
  [EnemyType.Phishing]: {
    type: EnemyType.Phishing,
    name: 'Phishing',
    hp: 40,
    speed: 50,
    damageToHub: 8,
    reward: 12,
    stealth: false,
    armor: 0,
    color: COLORS.phishing,
    size: 9,
    spawnCooldown: 0,
  },
  [EnemyType.Ransomware]: {
    type: EnemyType.Ransomware,
    name: 'Ransomware',
    hp: 80,
    speed: 30,
    damageToHub: 20,
    reward: 25,
    stealth: false,
    armor: 2,
    color: COLORS.ransomware,
    size: 12,
    spawnCooldown: 0,
  },
  [EnemyType.DDoSBoss]: {
    type: EnemyType.DDoSBoss,
    name: 'DDoS Boss',
    hp: 300,
    speed: 20,
    damageToHub: 50,
    reward: 100,
    stealth: false,
    armor: 5,
    color: COLORS.ddosBoss,
    size: 18,
    spawnCooldown: 3,
  },
};
